import type { DayPlan } from "@/lib/types";

export const days: DayPlan[] = [
  {
    n: 1,
    dato: "2026-06-19",
    ugedag: "Fredag",
    titel: "Ankomst & Reykjavik",
    tema: "Land kl. 08.40 — hele dagen forude",
    beskrivelse:
      "I lander kl. 08.40, henter autocamperen hos Go Campers og kører ind til Reykjavik for at hente køletasken. Så går det løs: et 7-trins wellness-ritual i Sky Lagoon, hvalsafari i RIB-speedbåd, et bad i Reykjadalurs varme flod og smukke billeder af Sólfar i aftensolen. Pølser ved Hallgrímskirkja til aftensmad.",
    emoji: "🛬",
    arrival: "08:40",
    routeIds: ["sky-lagoon", "hvalsafari-rib", "reykjadalur"],
    restaurantIds: ["baejarins-beztu"],
    poiIds: ["solfar", "hallgrimskirkja", "camp-reykjavik"],
    tips: [
      "Henter bil + tilbehør kl. 10.00 — handl evt. bagefter",
      "Køletaske hentes på Vatnsmýrarvegur 10 (åbent 9-17)",
      "Sky Lagoon kl. 12.00 — afsæt 30 min ekstra til bad og tøjskifte",
      "Hvalsafari: tjek ind kl. 15.30 til afgang kl. 16",
    ],
  },
  {
    n: 2,
    dato: "2026-06-20",
    ugedag: "Lørdag",
    titel: "Højlandet — Kerlingarfjöll",
    tema: "Heldagstur til de farverige bjerge",
    beskrivelse:
      "En guidet heldagstur dybt ind i højlandet til Kerlingarfjölls farvede rhyolit-bjerge. Undervejs stopper vi ved Gullfoss, svømmer i en af højlandets varme kilder og kommer forbi de berømte gejsere. Frokost på Highland Base. Retur i Reykjavik ca. 20.30, så videre til camping i Selfoss.",
    emoji: "⛰️",
    routeIds: ["kerlingarfjoll-tour"],
    restaurantIds: ["highland-base"],
    poiIds: ["gullfoss", "geysir", "camp-selfoss"],
    tips: [
      "Opsamling Skógarhlíð 10 kl. 8.30 — find parkering i god tid",
      "Hold øje med bussen 'Highland Base — Kerlingarfjöll'",
      "Pak et par snacks til turen",
      "Kør ad vej 34 ned langs sydkysten til Selfoss",
    ],
    weatherDependent: true,
  },
  {
    n: 3,
    dato: "2026-06-21",
    ugedag: "Søndag",
    titel: "Landmannalaugar & Skógafoss",
    tema: "Super-Jeep i højlandet + sydkystens ikon",
    beskrivelse:
      "Super-Jeep safari til det farverige Landmannalaugar — forbi en varm kilde, et krater og Hekla-vulkanen. Retur ca. 16.30, en kort byvandring i Selfoss (Skyrland), og så mod sydkysten til det 60 m høje Skógafoss. Gå de 370 trin til toppen for udsigten.",
    emoji: "🚙",
    routeIds: ["landmannalaugar-jeep", "skogafoss-trappen"],
    restaurantIds: ["skyrland"],
    poiIds: ["hekla", "selfoss", "camp-skogar"],
    alternativeRouteIds: [],
    tips: [
      "Lav madpakker til dagens tur",
      "Opsamling N1 Selfoss kl. 9.30 — badetøj med til den varme kilde",
      "Tag billeder af Skógafoss fra vejen over lupin-engene",
      "Keder I jer? Kvernufoss ligger ikke langt derfra",
    ],
  },
  {
    n: 4,
    dato: "2026-06-22",
    ugedag: "Mandag",
    titel: "Sydkysten — lunder, sort sand & gletsjere",
    tema: "Ægte natur og nuttede søpapegøjer",
    beskrivelse:
      "En dag i ægte islandsk natur. Start ved Dyrhólaey med det fotograferede fyrtårn, elefantklippen og søpapegøjer. Videre til den sorte strand Reynisfjara, frokost i Vík (Saga Museum + den fine kirke), og østpå forbi Rauðárfoss og Stjórnarfoss. Slut ved Diamond Beach / Jökulsárlón i midnatssolen og overnat ved Skaftafell.",
    emoji: "🐧",
    routeIds: ["skaftafell-sjonarnipa"],
    restaurantIds: [],
    poiIds: [
      "dyrholaey",
      "reynisfjara",
      "vik",
      "raudarfoss",
      "stjornarfoss",
      "diamond-beach",
      "camp-skaftafell",
    ],
    tips: [
      "Reynisfjara: hold god afstand til de farlige 'sneaker waves'",
      "Vík: snup en sort pizza, kaffe i skolebussen, og find mineralbutikken",
      "Saga Museum i Vík: åbent 10.00-17.00",
      "Skaftafell: gå evt. til Skaftafellsjökull og Sjónarnípa Viewpoint",
    ],
    weatherDependent: true,
  },
  {
    n: 5,
    dato: "2026-06-23",
    ugedag: "Tirsdag",
    titel: "Gletsjerlaguner & tomatfarm",
    tema: "Isbjerge, alfehuse og aftensmad i drivhuset",
    beskrivelse:
      "Zodiac-bådtur mellem de blå isbjerge på Jökulsárlón kl. 11.10, så et kig på den mindre Fjallsárlón og den hyggelige græstørvskirke Hofskirkja. Eftermiddag i Secret Lagoon med besøg ved de små alfehuse, og aftensmad i Friðheimars tomatdrivhus. Overnatning i Reykholt.",
    emoji: "🧊",
    routeIds: ["jokulsarlon-zodiac", "secret-lagoon"],
    restaurantIds: ["fridheimar"],
    poiIds: ["jokulsarlon", "fjallsarlon", "hofskirkja", "camp-reykholt"],
    tips: [
      "Kør tidligt hvis I vil gå op langs Jökulsárlón før bådturen",
      "Check ind ved Ice Lagoon-trucken så I undgår kø",
      "Secret Lagoon åbent 10.00-20.00 — afsæt 30 min til bad",
      "Friðheimar: bord bookes — åbent 12.00-22.00",
    ],
  },
  {
    n: 6,
    dato: "2026-06-24",
    ugedag: "Onsdag",
    titel: "Den Gyldne Cirkel → Snæfellsnes",
    tema: "Rugbrød, snorkling og midnatssol ved Kirkjufell",
    beskrivelse:
      "En lang og fantastisk dag: rugbrød bagt i jorden ved Laugarvatn (vær der kl. 10.05), snorkling mellem kontinenterne i Silfra, champignon-frokost på Farmers Bistro, et bad i Hrunalaug, og vandfaldene Hraunfossar, Barnafoss og Glanni. Aften på Snæfellsnes med Búðakirkja og Kirkjufell under midnatssolen.",
    emoji: "🤿",
    routeIds: ["silfra-snorkel"],
    restaurantIds: ["farmers-bistro", "lindin-laugarvatn"],
    poiIds: [
      "laugarvatn",
      "thingvellir",
      "hrunalaug",
      "hraunfossar",
      "barnafoss",
      "glanni",
      "budakirkja",
      "kirkjufell",
      "camp-grundarfjordur",
    ],
    tips: [
      "Silfra: vær der kl. 12.00, mød 15 min før (11.45)",
      "Farmers Bistro: bord kl. 16.00 — køkken lukker 16.40",
      "Hrunalaug kan kortes ned til 30 min hvis tiden er knap",
      "Overvej en aftengåtur (3,7 km) til Kirkjufell fra campingpladsen",
    ],
    weatherDependent: true,
  },
  {
    n: 7,
    dato: "2026-06-25",
    ugedag: "Torsdag",
    titel: "Færge til Vestfjordene",
    tema: "Baldur over Breiðafjörður + skjulte varme kilder",
    beskrivelse:
      "Fotostop ved Kolgrafarfjörður (vejen ser ud som et sværd), så færgen Baldur fra Stykkishólmur kl. 11.00 med pit-stop på Flatey. Vi lander i Brjánslækur og kører gennem Vestfjordene: badestop ved Hellulaug og Reykjafjarðarlaug, den forladte A-house, Fossfjörður og til sidst Vestfjordenes juvel Dynjandi. Overnatning i Tálknafjörður.",
    emoji: "⛴️",
    routeIds: ["dynjandi-hike"],
    restaurantIds: ["fiskabudin-flatey"],
    poiIds: [
      "kolgrafarfjordur",
      "flatey",
      "hellulaug",
      "reykjafjardarlaug",
      "a-house",
      "fossfjordur",
      "camp-talknafjordur",
    ],
    ferryIds: ["baldur"],
    tips: [
      "Vær ved færgen kl. 10.45 (afgang 11.00)",
      "Hold øje med søpapegøjer og hvaler — særligt ved Flatey",
      "Hellulaug findes på Google Maps, ikke Apple Kort",
      "Dynjandi: husk vandreskoene til opstigningen (200 m)",
    ],
  },
  {
    n: 8,
    dato: "2026-06-26",
    ugedag: "Fredag",
    titel: "Rauðasandur & tilbage mod Reykjavik",
    tema: "Den gyldne strand og et sidste varmt bad",
    beskrivelse:
      "Tidlig start til den gyldne strand Rauðasandur (kør forsigtigt på de stejle grusveje). Så den lange, smukke køretur øst om og ned mod Reykjavik med et badestop ved Hvammsvík Hot Springs. Undervejs et svingom til den hvide Reynivallakirkja og det lille Helgufoss-vandfald. Måske en aktiv vulkan ved Grindavík?",
    emoji: "🏖️",
    routeIds: ["hvammsvik"],
    restaurantIds: [],
    poiIds: ["raudasandur", "reynivallakirkja", "helgufoss"],
    tips: [
      "Rauðasandur-vejen: stejle hårnålesving uden autoværn — kør i 1.-2. gear",
      "Overvej et stop ved gårdbutikken Handverksfélagið Assa (åbent fre 10-18)",
      "Hvammsvík bookes når I nærmer jer — åbent 10.00-22.00",
      "Helgufoss i Mosfellsdalur er perfekt til en picnic",
    ],
    weatherDependent: true,
    planB:
      "Hvis vejret er skidt på Rauðasandur, så drop stranden og brug tiden på Hvammsvík og et hyggeligt sted at spise i Reykjavik.",
  },
  {
    n: 9,
    dato: "2026-06-27",
    ugedag: "Lørdag",
    titel: "Lunder & farvel Island",
    tema: "Rejsens sidste tur — søpapegøjer fra havnen",
    beskrivelse:
      "Rejsens sidste oplevelse: en RIB-tur fra Reykjaviks gamle havn ud for at se søpapegøjer (lunder). Bagefter afleveres køletasken, og vi kører forbi Hvalsneskirkja vest for Keflavik, inden bilen afleveres kl. 13.30 (husk at tanke!) og flyet går kl. 16.30. Gå gensyn, Island!",
    emoji: "✈️",
    departure: "16:30",
    routeIds: ["puffin-rib"],
    restaurantIds: [],
    poiIds: ["hvalsneskirkja"],
    tips: [
      "Vær ved havnen kl. 8.30 (Ægisgarður 7)",
      "Aflever køletasken: Vatnsmýrarvegur 10",
      "Aflever bilen kl. 13.30 — HUSK at tanke først!",
      "Fly afgang kl. 16.30 — vær i god tid i lufthavnen",
    ],
  },
];

export const dayByN = (n: number) => days.find((d) => d.n === n);
