import type { Poi } from "@/lib/types";
import { img } from "./images";

export const pois: Poi[] = [
  // ── Reykjavik ───────────────────────────────────────────────────────────────
  {
    id: "solfar",
    name: "Sólfar (Sun Voyager)",
    area: "Reykjavík",
    coord: [64.1426, -21.9224],
    category: "kultur",
    description:
      "Den berømte vikingeskibs-skulptur ved havnefronten. Smukkest i aftensolen — perfekt til et par billeder før campingpladsen.",
    freeAccess: true,
    emoji: "⛵",
    image: img("solfar"),
  },
  {
    id: "hallgrimskirkja",
    name: "Hallgrímskirkja",
    area: "Reykjavík",
    coord: [64.1417, -21.9266],
    category: "kultur",
    description:
      "Reykjaviks ikoniske kirke. Lige ved siden af ligger pølsevognen Víkinga Pylsur. Godt udgangspunkt for en aftentur i byen.",
    freeAccess: true,
    emoji: "⛪",
  },

  // ── Højlandet & Den Gyldne Cirkel ───────────────────────────────────────────
  {
    id: "gullfoss",
    name: "Gullfoss",
    area: "Suðurland",
    coord: [64.3271, -20.1199],
    category: "fotografi",
    description:
      "Det 'gyldne vandfald' styrter i to trin ned i en dyb kløft — et af Islands mest imponerende. Stop på højlandsturen dag 2.",
    freeAccess: true,
    emoji: "💧",
    image: img("gullfoss"),
  },
  {
    id: "geysir",
    name: "Geysir & Strokkur",
    area: "Suðurland",
    coord: [64.3104, -20.3024],
    category: "fotografi",
    description:
      "Det geotermiske område hvor Strokkur sprøjter kogende vand 15-20 m i vejret hvert par minutter. Ordet 'gejser' kommer herfra.",
    freeAccess: true,
    emoji: "⛲",
    image: img("geysir"),
  },
  {
    id: "hekla",
    name: "Hekla-vulkanen",
    area: "Højlandet",
    coord: [63.9925, -19.6656],
    category: "udsigt",
    description:
      "Islands mest aktive vulkan, kaldet 'Porten til Helvede' i middelalderen. Passeres på super-Jeep-turen til Landmannalaugar.",
    freeAccess: true,
    emoji: "🌋",
    image: img("hekla"),
  },
  {
    id: "thingvellir",
    name: "Þingvellir Nationalpark",
    area: "Suðurland",
    coord: [64.2558, -21.1182],
    category: "kultur",
    description:
      "UNESCO-verdensarv hvor det islandske Alting blev grundlagt år 930 — og hvor de to kontinentalplader trækker fra hinanden. Island bliver 2-3 cm bredere hvert år.",
    freeAccess: true,
    emoji: "🏛️",
    image: img("thingvellir"),
  },

  // ── Sydkysten ───────────────────────────────────────────────────────────────
  {
    id: "skyrland",
    name: "Selfoss & Skyrland",
    area: "Suðurland",
    coord: [63.9333, -20.9971],
    category: "bygd",
    description:
      "Sydkystens største by ved floden Ölfusá. Tag en byvandring og besøg Skyrland, der fortæller historien om Islands berømte skyr.",
    freeAccess: false,
    costDKK: 120,
    emoji: "🥛",
  },
  {
    id: "dyrholaey",
    name: "Dyrhólaey",
    area: "Sydkysten",
    coord: [63.4015, -19.1289],
    category: "udsigt",
    description:
      "Det mest fotograferede fyrtårn på Island, en kæmpe stenbue (elefantklippen) og masser af søpapegøjer (lunder). Betagende udsigt over det sorte sand.",
    freeAccess: true,
    emoji: "🐧",
    image: img("dyrholaey"),
  },
  {
    id: "reynisfjara",
    name: "Reynisfjara — den sorte strand",
    area: "Sydkysten",
    coord: [63.4027, -19.0448],
    category: "udsigt",
    description:
      "Verdensberømt sort sandstrand med kæmpe basaltsøjler og dramatiske bølger. Oplev havets magt — men hold god afstand til de farlige 'sneaker waves'.",
    freeAccess: true,
    emoji: "🏖️",
    image: img("blackBeach"),
  },
  {
    id: "vik",
    name: "Vík í Mýrdal",
    area: "Sydkysten",
    coord: [63.4186, -19.006],
    category: "bygd",
    description:
      "Hyggelig by ved sydkysten med den fine kirke på bakken, omringet af lupiner. Saga Museum (åbent 10-17), sort pizza og kaffe i skolebussen. Find også mineralbutikken.",
    freeAccess: true,
    emoji: "🏘️",
    image: img("vik"),
  },
  {
    id: "raudarfoss",
    name: "Rauðárfoss",
    area: "Sydkysten",
    coord: [63.7866, -18.0894],
    category: "fotografi",
    description:
      "Det 'røde vandfald' nær Kirkjubæjarklaustur — en mindre kendt perle på vejen østpå.",
    freeAccess: true,
    emoji: "💦",
    image: img("raudarfoss"),
  },
  {
    id: "stjornarfoss",
    name: "Stjórnarfoss",
    area: "Sydkysten",
    coord: [63.7869, -18.0686],
    category: "fotografi",
    description:
      "Charmerende lille vandfald ved Kirkjubæjarklaustur — et roligt stop væk fra de store turistmasser.",
    freeAccess: true,
    emoji: "💦",
    image: img("stjornarfoss"),
  },

  // ── Vatnajökull / gletsjerlagunerne ─────────────────────────────────────────
  {
    id: "diamond-beach",
    name: "Diamond Beach",
    area: "Vatnajökull",
    coord: [64.0438, -16.1793],
    category: "fotografi",
    description:
      "Den sorte strand hvor klare isstykker fra Jökulsárlón skyller op og glimter som diamanter. Overvej et besøg i midnatssolen.",
    freeAccess: true,
    emoji: "💎",
    image: img("diamondBeach"),
  },
  {
    id: "jokulsarlon",
    name: "Jökulsárlón gletsjerlagune",
    area: "Vatnajökull",
    coord: [64.0784, -16.2306],
    category: "udsigt",
    description:
      "Islands dybeste sø, fyldt med blå isbjerge der kælver fra Breiðamerkurjökull. Gå op langs østsiden af gletsjeren for den bedste udsigt.",
    freeAccess: true,
    emoji: "🧊",
    image: img("glacierLagoon"),
  },
  {
    id: "fjallsarlon",
    name: "Fjallsárlón",
    area: "Vatnajökull",
    coord: [64.0136, -16.3819],
    category: "udsigt",
    description:
      "Mindre og mere intim gletsjerlagune end Jökulsárlón — her kommer man helt tæt på gletsjertungen.",
    freeAccess: true,
    emoji: "🏔️",
    image: img("fjallsarlon"),
  },
  {
    id: "hofskirkja",
    name: "Hofskirkja",
    area: "Vatnajökull",
    coord: [63.923, -16.7036],
    category: "kultur",
    description:
      "En af Islands sidste græstørvskirker (1884) med tag af torv. Lille og idyllisk — kort gåtur fra parkeringen.",
    freeAccess: true,
    emoji: "⛪",
    image: img("hofskirkja"),
  },

  // ── Den Gyldne Cirkel & Vesturland ──────────────────────────────────────────
  {
    id: "laugarvatn",
    name: "Laugarvatn — rugbrød i jorden",
    area: "Suðurland",
    coord: [64.2167, -20.7333],
    category: "kultur",
    description:
      "Geotermisk rugbrødsoplevelse ved Fontana Spa: se hvordan rugbrødet bages i den varme jord — med smagsprøver. Vær der kl. 10.05!",
    freeAccess: false,
    costDKK: 150,
    emoji: "🍞",
    image: img("laugarvatn"),
  },
  {
    id: "hrunalaug",
    name: "Hrunalaug varm kilde",
    area: "Suðurland",
    coord: [64.1547, -20.2522],
    category: "udsigt",
    description:
      "Lille, hyggelig naturlig varm kilde nær Flúðir. Et autentisk bad i naturen — kan kortes ned til 30 min hvis tiden er knap.",
    freeAccess: false,
    costDKK: 30,
    emoji: "♨️",
    image: img("hrunalaug"),
  },
  {
    id: "hraunfossar",
    name: "Hraunfossar",
    area: "Vesturland",
    coord: [64.7028, -20.9783],
    category: "fotografi",
    description:
      "Utallige små vandfald siver ud af lavamarken og løber i klare tråde ned i floden — klædt i sommerfarver. Helt unikt syn.",
    freeAccess: true,
    emoji: "💦",
    image: img("hraunfossar"),
  },
  {
    id: "barnafoss",
    name: "Barnafoss",
    area: "Vesturland",
    coord: [64.7036, -20.9706],
    category: "fotografi",
    description:
      "Vildt og brusende vandfald lige ved siden af Hraunfossar — turkist vand der pisker gennem smalle klippeformationer.",
    freeAccess: true,
    emoji: "🌊",
    image: img("barnafoss"),
  },
  {
    id: "glanni",
    name: "Glanni",
    area: "Vesturland",
    coord: [64.7686, -21.2783],
    category: "udsigt",
    description:
      "Smukt vandfald ved Bifröst med udsigtspunkt lige ved pladsen. Stien følger kanten — gå frem og tilbage for den bedste udsigt.",
    freeAccess: true,
    emoji: "💧",
    image: img("glanni"),
  },

  // ── Snæfellsnes ─────────────────────────────────────────────────────────────
  {
    id: "budakirkja",
    name: "Búðakirkja",
    area: "Snæfellsnes",
    coord: [64.8211, -23.3847],
    category: "kultur",
    description:
      "Den berømte sorte kirke alene på lavamarken — en af Islands mest fotograferede bygninger. Der er kun plads til 50 mennesker indeni.",
    freeAccess: true,
    emoji: "⛪",
    image: img("budakirkja"),
  },
  {
    id: "kirkjufell",
    name: "Kirkjufell & Kirkjufellsfoss",
    area: "Snæfellsnes",
    coord: [64.9275, -23.3074],
    category: "fotografi",
    description:
      "Islands mest fotograferede bjerg sammen med de skønne vandfald — og hvor fedt er det lige, at vi ser det under midnatssolen. Ankomst ca. kl. 2.",
    freeAccess: true,
    emoji: "🏔️",
    image: img("kirkjufell"),
  },

  // ── Vestfjordene ────────────────────────────────────────────────────────────
  {
    id: "kolgrafarfjordur",
    name: "Kolgrafarfjörður viewpoint",
    area: "Snæfellsnes",
    coord: [64.9608, -23.1031],
    category: "udsigt",
    description:
      "Vejen over fjorden ser ud som et sværd, der skærer gennem vandet (Eyrbyggja på kortet). Kort fotostop på vej mod færgen.",
    freeAccess: true,
    emoji: "🗡️",
    image: img("kolgrafarfjordur"),
  },
  {
    id: "flatey",
    name: "Flatey",
    area: "Breiðafjörður",
    coord: [65.3761, -22.9261],
    category: "bygd",
    description:
      "Lille idyllisk ø med pit-stop på færgeturen. Fiskabúðin sælger fisk, brød og nips. Hold øje med søpapegøjer og hvaler omkring øen.",
    freeAccess: true,
    emoji: "🐟",
    image: img("flatey"),
  },
  {
    id: "hellulaug",
    name: "Hellulaug varm kilde",
    area: "Vestfjordene",
    coord: [65.5772, -23.1597],
    category: "udsigt",
    description:
      "Naturlig varm kilde lige ved havet nær Flókalundur. Findes på Google Maps (men ikke på Apple Kort) — et roligt badestop.",
    freeAccess: true,
    emoji: "♨️",
    image: img("hellulaug"),
  },
  {
    id: "reykjafjardarlaug",
    name: "Reykjafjarðarlaug",
    area: "Vestfjordene",
    coord: [65.6333, -23.5167],
    category: "udsigt",
    description:
      "Både en naturlig varm kilde og et anlagt bassin i en afsidesliggende region. Ingen organiserede ture stopper her — ren ro og fred.",
    freeAccess: true,
    emoji: "♨️",
    image: img("reykjafjardarlaug"),
  },
  {
    id: "a-house",
    name: "The A-house (forladt lade)",
    area: "Vestfjordene",
    coord: [65.6206, -23.5519],
    category: "kultur",
    description:
      "En rustik, forladt lade i Arnarfjörður — et smukt billede på Islands landlige fortid og arkitektur, omgivet af dramatiske fjorde.",
    freeAccess: true,
    emoji: "🏚️",
    image: img("aHouse"),
  },
  {
    id: "fossfjordur",
    name: "Fossfjörður vandfald (Foss)",
    area: "Vestfjordene",
    coord: [65.5814, -23.4561],
    category: "fotografi",
    description:
      "Vandfaldet løber ned ad en klippefyldt skråning i flere trin — et populært fotomotiv lige ned til vandkanten.",
    freeAccess: true,
    emoji: "💦",
    image: img("fossfjordur"),
  },

  // ── Tilbage mod Reykjavik ───────────────────────────────────────────────────
  {
    id: "raudasandur",
    name: "Rauðasandur (den gyldne strand)",
    area: "Vestfjordene",
    coord: [65.4742, -24.0494],
    category: "udsigt",
    description:
      "Kilometerlang strand med rødgyldent sand i stærk kontrast til det blå hav. Vejen ned har stejle hårnålesving uden autoværn — kør forsigtigt.",
    freeAccess: true,
    emoji: "🏖️",
    image: img("raudasandur"),
  },
  {
    id: "reynivallakirkja",
    name: "Reynivallakirkja",
    area: "Hvalfjörður",
    coord: [64.3236, -21.3081],
    category: "kultur",
    description:
      "Hvid trækirke med grønne lister på en græsklædt bakke i Kjós. Kirken er dokumenteret tilbage til ca. år 1200; den nuværende er fra 1859.",
    freeAccess: true,
    emoji: "⛪",
    image: img("reynivallakirkja"),
  },
  {
    id: "helgufoss",
    name: "Helgufoss",
    area: "Reykjavík",
    coord: [64.2089, -21.4047],
    category: "fotografi",
    description:
      "Et dejligt lille (12 m) vandfald i Mosfellsdalur — fantastisk til en picnic i rolige, maleriske omgivelser.",
    freeAccess: true,
    emoji: "💦",
    image: img("helgufoss"),
  },
  {
    id: "hvalsneskirkja",
    name: "Hvalsneskirkja",
    area: "Reykjanes",
    coord: [63.9772, -22.69],
    category: "kultur",
    description:
      "Smuk stenkirke fra 1887 vest for Keflavik — et sidste stop før bilen afleveres og flyet går.",
    freeAccess: true,
    emoji: "⛪",
  },

  // ── Campingpladser (overnatning skifter hver nat) ───────────────────────────
  {
    id: "camp-reykjavik",
    name: "Reykjavik Campsite",
    area: "Reykjavík",
    coord: [64.1399, -21.8717],
    category: "praktisk",
    description: "Nat 1 — nær svømmehallen og stadion i Laugardalur.",
    freeAccess: false,
    costDKK: 150,
    emoji: "⛺",
    image: img("reykjavik"),
  },
  {
    id: "camp-selfoss",
    name: "Camping Selfoss (Gesthús)",
    area: "Suðurland",
    coord: [63.9357, -20.9876],
    category: "praktisk",
    description: "Nat 2 — god base til at nyde området og sydkysten.",
    freeAccess: false,
    costDKK: 150,
    emoji: "⛺",
  },
  {
    id: "camp-skogar",
    name: "Skógar Camping",
    area: "Sydkysten",
    coord: [63.529, -19.509],
    category: "praktisk",
    description: "Nat 3 — lige ved foden af Skógafoss.",
    freeAccess: false,
    costDKK: 150,
    emoji: "⛺",
  },
  {
    id: "camp-skaftafell",
    name: "Skaftafell Camping",
    area: "Vatnajökull",
    coord: [64.0166, -16.9665],
    category: "praktisk",
    description: "Nat 4 — i Vatnajökull Nationalpark, tæt på gletsjervandringerne.",
    freeAccess: false,
    costDKK: 150,
    emoji: "⛺",
  },
  {
    id: "camp-reykholt",
    name: "Reykholt Campingplads",
    area: "Suðurland",
    coord: [64.1783, -20.4461],
    category: "praktisk",
    description: "Nat 5 — i Biskupstungur, tæt på Den Gyldne Cirkel.",
    freeAccess: false,
    costDKK: 150,
    emoji: "⛺",
    image: img("reykholt"),
  },
  {
    id: "camp-grundarfjordur",
    name: "Grundarfjörður Camping",
    area: "Snæfellsnes",
    coord: [64.922, -23.254],
    category: "praktisk",
    description: "Nat 6 — kort gåtur (3,7 km) til Kirkjufell i midnatssolen.",
    freeAccess: false,
    costDKK: 150,
    emoji: "⛺",
    image: img("grundarfjordur"),
  },
  {
    id: "camp-talknafjordur",
    name: "Tálknafjörður Campsite",
    area: "Vestfjordene",
    coord: [65.623, -23.81],
    category: "praktisk",
    description: "Nat 7 — fredelig fjord-camping i Vestfjordene.",
    freeAccess: false,
    costDKK: 150,
    emoji: "⛺",
    image: img("talknafjordur"),
  },
];

export const poiById = (id: string) => pois.find((p) => p.id === id);
