import type { Route } from "@/lib/types";
import { img } from "./images";

// "Ruter" på Island = de aktive oplevelser og vandringer i rejseplanen
// (varme bade, bådture, super-jeep, snorkling og fodture). Priser er omtrentlige
// pr. person i DKK — tjek altid aktuel pris ved booking.
export const routes: Route[] = [
  {
    id: "sky-lagoon",
    slug: "sky-lagoon",
    name: "Sky Lagoon — 7-trins ritual",
    area: "Reykjavík",
    startCoord: [64.1165, -21.9464],
    distanceKm: 0,
    durationMin: 150,
    elevationM: 0,
    difficulty: "let",
    costDKK: 850,
    costNote: "Pure/Sér-pakke pr. person. PDF: ~30.582 ISK for to + gebyr.",
    description:
      "Ultimativ islandsk wellness lige uden for Reykjavik. Det 7-trins Skjól-ritual: Laug (lagune), Kuldi (koldt gys), Ylur (sauna), Súld (kold tåge), Mýkt (blød scrub), Gufa (dampbad) og Sturt (afslutning) — med uendelig udsigt over Atlanten.",
    tips: [
      "Afsæt 30 min ekstra til bad og tøjskifte",
      "Book tidspunkt på forhånd — kl. 12.00 dag 1",
      "Tag det roligt — gennemfør ritualet i rækkefølge",
    ],
    bookingUrl: "https://www.skylagoon.com",
    emoji: "♨️",
    badge: "Booket",
    image: img("skyLagoon"),
  },
  {
    id: "hvalsafari-rib",
    slug: "hvalsafari-rib",
    name: "Hvalsafari med RIB-speedbåd",
    area: "Reykjavík",
    startCoord: [64.1514, -21.9443],
    distanceKm: 0,
    durationMin: 120,
    elevationM: 0,
    difficulty: "let",
    costDKK: 700,
    costNote: "Pr. person. Afgang fra Old Harbour House, Ægisgarður 2.",
    description:
      "Spændende tur i RIB-speedbåd ud i Faxaflói-bugten. Måske ser vi pukkelhvaler, spækhuggere, vågehvaler, delfiner eller marsvin — og altid den smukke udsigt ind mod Reykjaviks kyst.",
    tips: [
      "Tjek ind 30 min før afgang (kl. 15.30 til kl. 16-turen)",
      "Scan QR-koden på billetten i selvbetjeningskiosken",
      "Tag varmt tøj på — det blæser på vandet",
    ],
    bookingUrl:
      "https://www.getyourguide.com/da-dk/reykjavik-l30/reykjavik-hvalsafari-med-rib-speedboat-t402119/",
    emoji: "🐋",
    badge: "Booket",
    image: img("whaleRib"),
  },
  {
    id: "reykjadalur",
    slug: "reykjadalur-hot-river",
    name: "Reykjadalur — den varme flod",
    area: "Suðurland",
    startCoord: [64.0238, -21.2122],
    distanceKm: 6,
    durationMin: 90,
    elevationM: 250,
    difficulty: "middel",
    costDKK: 0,
    description:
      "En lille gåtur på ca. 45 min op ad bjerget fører til en varm flod, hvor man kan bade midt i naturen. Jo længere op mod bjerget I går, jo varmere bliver vandet.",
    tips: [
      "Tag badetøj og håndklæde med i rygsækken",
      "Der er træplanker til at skifte tøj ved floden",
      "Gode vandresko — stien kan være mudret",
    ],
    emoji: "🏞️",
    badge: "Gratis",
    image: img("reykjadalur"),
  },
  {
    id: "kerlingarfjoll-tour",
    slug: "kerlingarfjoll-heldagstur",
    name: "Kerlingarfjöll — højlands-heldagstur",
    area: "Højlandet",
    startCoord: [64.6333, -19.3167],
    distanceKm: 0,
    durationMin: 720,
    elevationM: 0,
    difficulty: "let",
    costDKK: 1200,
    costNote: "Guidet heldagstur pr. person. Opsamling Skógarhlíð 10, kl. 8.30.",
    description:
      "Heldagstur til højlandets farverige rhyolit-bjerge ved Kerlingarfjöll. På turen stopper vi ved Gullfoss, svømmer i en af højlandets varme kilder og kommer forbi gejserne. Frokost på Highland Base.",
    tips: [
      "Hold øje med bussen med skiltet 'Highland Base — Kerlingarfjöll'",
      "Pak et par snacks til turen",
      "Vi er retur i Reykjavik ca. 20.30",
    ],
    bookingUrl: "https://www.kerlingarfjoll.is",
    emoji: "⛰️",
    badge: "Heldagstur",
    image: img("kerlingarfjoll"),
  },
  {
    id: "landmannalaugar-jeep",
    slug: "landmannalaugar-super-jeep",
    name: "Landmannalaugar i super-Jeep",
    area: "Højlandet",
    startCoord: [63.9836, -19.0566],
    distanceKm: 0,
    durationMin: 420,
    elevationM: 0,
    difficulty: "let",
    costDKK: 1400,
    costNote: "Super-Jeep safari pr. person. Opsamling N1 Selfoss, kl. 9.30.",
    description:
      "Eventyr i super-Jeep til det farverige højland ved Landmannalaugar. Vi kommer bl.a. forbi en varm kilde, et krater og den berømte Hekla-vulkan. Retur ca. 16.30/17.00.",
    tips: [
      "Lav madpakker til dagens tur",
      "Badetøj med — der er en varm kilde undervejs",
      "Bilen kan ikke selv køre derop i juni — derfor super-Jeep",
    ],
    bookingUrl:
      "https://adventures.is/iceland/day-tours/super-jeeps/landmannalaugar-safari/",
    emoji: "🚙",
    badge: "Booket",
    image: img("landmannalaugar"),
  },
  {
    id: "skogafoss-trappen",
    slug: "skogafoss-trappen",
    name: "Skógafoss — trappen til toppen",
    area: "Sydkysten",
    startCoord: [63.532, -19.5114],
    distanceKm: 2,
    durationMin: 60,
    elevationM: 110,
    difficulty: "middel",
    costDKK: 0,
    description:
      "Det 60 m høje Skógafoss er et af Islands smukkeste vandfald. Trappen til toppen har 370 trin og belønner med en storslået udsigt. Kører I forbi lupin-engene, så stop og tag billeder.",
    tips: [
      "Keder I jer, ligger Kvernufoss ikke langt derfra",
      "Regnslag — der sprøjter meget vand ved bunden",
      "Campingpladsen ligger lige ved vandfaldet",
    ],
    emoji: "💦",
    badge: "370 trin",
    image: img("skogafoss"),
  },
  {
    id: "skaftafell-sjonarnipa",
    slug: "skaftafell-sjonarnipa",
    name: "Skaftafell → Sjónarnípa",
    area: "Vatnajökull",
    startCoord: [64.0159, -16.9667],
    distanceKm: 5.2,
    durationMin: 150,
    elevationM: 300,
    difficulty: "middel",
    costDKK: 0,
    description:
      "Vandring fra Skaftafell forbi Skaftafellsjökull-gletsjeren (Göngeleið, ca. 2,6 km) og videre til Sjónarnípa Viewpoint — et betagende syn over gletsjeren og naturen omkring den.",
    tips: [
      "Start fra Skaftafell besøgscenter",
      "Gode vandresko — stien stiger jævnt",
      "Tag madpakke og vand med",
    ],
    emoji: "🥾",
    image: img("skaftafell"),
  },
  {
    id: "jokulsarlon-zodiac",
    slug: "jokulsarlon-zodiac",
    name: "Jökulsárlón — zodiac-bådtur",
    area: "Vatnajökull",
    startCoord: [64.0784, -16.2306],
    distanceKm: 0,
    durationMin: 75,
    elevationM: 0,
    difficulty: "let",
    costDKK: 950,
    costNote: "Zodiac-bådtur pr. person. Mødested: den store blå Ice Lagoon-truck.",
    description:
      "Sejl mellem de blå isbjerge på gletsjerlagunen Jökulsárlón i en hurtig zodiac-båd. Bådtur kl. 11.10 (start 11.20), færdig ca. 12.40.",
    tips: [
      "Check ind når I kommer, så I undgår kø",
      "Varmt tøj og vandtæt jakke — det er koldt på lagunen",
      "Husk Diamond Beach lige ved siden af",
    ],
    bookingUrl:
      "https://adventures.is/iceland/day-tours/jokulsarlon-glacier-lagoon-tours/",
    emoji: "🧊",
    badge: "Booket",
    image: img("jokulsarlon"),
  },
  {
    id: "silfra-snorkel",
    slug: "silfra-snorkling",
    name: "Silfra — snorkling mellem kontinenter",
    area: "Þingvellir",
    startCoord: [64.2557, -21.1187],
    distanceKm: 0,
    durationMin: 150,
    elevationM: 0,
    difficulty: "middel",
    costDKK: 1100,
    costNote: "Snorkling i tørdragt pr. person. Mød 15 min før, dvs. 11.45.",
    description:
      "Snorkl i den krystalklare sprække Silfra i Þingvellir Nationalpark — mellem den nordamerikanske og eurasiske kontinentalplade. Vandet er glacialt og sigtbarheden over 100 m.",
    tips: [
      "Vær der kl. 12.00 — mød 15 min før",
      "Tørdragt holder dig tør; tag varmt undertøj på",
      "Færdig ca. kl. 14.30",
    ],
    warnings: ["Iskoldt vand (~2-4°C)", "Kræver at man kan svømme roligt"],
    bookingUrl: "https://www.dive.is/diving-tours/snorkeling-silfra/",
    emoji: "🤿",
    badge: "Booket",
    image: img("silfra"),
  },
  {
    id: "secret-lagoon",
    slug: "secret-lagoon",
    name: "Secret Lagoon (Gamla Laugin)",
    area: "Suðurland",
    startCoord: [64.1378, -20.3094],
    distanceKm: 0,
    durationMin: 90,
    elevationM: 0,
    difficulty: "let",
    costDKK: 250,
    costNote: "Entré pr. person. Åbent 10.00-20.00.",
    description:
      "Islands ældste swimmingpool — en naturlig geotermisk lagune i Flúðir. Afslappet og hyggelig, omgivet af dampende kilder. Besøg de små alfehuse i nærheden.",
    tips: [
      "Afsæt tid til bad og tøjskifte (30 min)",
      "Mindre turistet end Blue Lagoon",
      "Perfekt før aftensmaden på Friðheimar",
    ],
    bookingUrl: "https://secretlagoon.is",
    emoji: "♨️",
    image: img("secretLagoon"),
  },
  {
    id: "dynjandi-hike",
    slug: "dynjandi",
    name: "Dynjandi — Vestfjordenes juvel",
    area: "Vestfjordene",
    startCoord: [65.7333, -23.2056],
    distanceKm: 1,
    durationMin: 60,
    elevationM: 200,
    difficulty: "middel",
    costDKK: 0,
    description:
      "Vestfjordenes største vandfald — 100 m højt og formet som et brudeslør. Under det ligger fem andre vandfald. Man kan vandre til toppen (200 m opstigning) forbi flere mindre fald.",
    tips: [
      "Husk vandreskoene — det er en rigtig opstigning",
      "Nationalt monument siden 1981 — pas på naturen",
      "Tag tid til at se alle de små fald på vejen op",
    ],
    emoji: "🌊",
    badge: "Juvelen",
    image: img("dynjandi"),
  },
  {
    id: "hvammsvik",
    slug: "hvammsvik-hot-springs",
    name: "Hvammsvík Hot Springs",
    area: "Hvalfjörður",
    startCoord: [64.3719, -21.4869],
    distanceKm: 0,
    durationMin: 120,
    elevationM: 0,
    difficulty: "let",
    costDKK: 550,
    costNote: "Entré pr. person. Åbent 10.00-22.00. Bookes på vejen tilbage.",
    description:
      "Naturlige varme bassiner lige ned til havet i Hvalfjörður — et perfekt badestop på vejen tilbage mod Reykjavik. Vandstanden i nogle bassiner ændrer sig med tidevandet.",
    tips: [
      "Book når I nærmer jer på køreturen",
      "Tag et stop undervejs hvis I ser noget spændende",
      "Skift mellem varme bassiner og det kolde hav",
    ],
    bookingUrl: "https://www.hvammsvik.com",
    emoji: "♨️",
    image: img("hvammsvik"),
  },
  {
    id: "puffin-rib",
    slug: "lunde-rib",
    name: "Lunde-safari med RIB-båd",
    area: "Reykjavík",
    startCoord: [64.1514, -21.9443],
    distanceKm: 0,
    durationMin: 90,
    elevationM: 0,
    difficulty: "let",
    costDKK: 600,
    costNote: "Pr. person. Mødested Reykjaviks gamle havn, Ægisgarður 7.",
    description:
      "Rejsens sidste tur: ud at se søpapegøjer (lunder) på en RIB-båd fra Reykjaviks gamle havn. I små grupper sejler vi ud til øerne hvor lundefuglene yngler.",
    tips: [
      "Vær der kl. 8.30 (afgang 9.00-10.00)",
      "Aflever køletasken i Reykjavik bagefter",
      "Sidste oplevelse før bilen afleveres kl. 13.30",
    ],
    bookingUrl:
      "https://www.getyourguide.com/da-dk/reykjavik-l30/rib-krydstogt-med-lundefugle-i-sma-grupper-fra-reykjavik-t59202/",
    emoji: "🐧",
    badge: "Booket",
    image: img("puffins"),
  },
];

export const routeById = (id: string) => routes.find((r) => r.id === id);
export const routeBySlug = (slug: string) => routes.find((r) => r.slug === slug);
